##### dev 配置 #######
spring:
  profiles: prod

  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/snow_admin?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: Root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#是否需要输入验证码
captcha:
  enable: true